import type { Project } from './types'

const P = '/projects'

/**
 * All projects, in the order they appear in the opening slideshow and the
 * work index. A project without an image appears in the index only.
 */
export const projects: Project[] = [
  {
    id: 'wayside',
    title: 'wayside.at',
    kind: 'AR development',
    client: 'Andrew Kastner, with Capital Fringe',
    year: '2025',
    lines: ['For Andrew Kastner', 'Kenilworth Aquatic Gardens, DC'],
    disciplines: ['Augmented', 'Geolocated', 'Browser'],
    about: 'Browser-based augmented reality for Kenilworth Aquatic Gardens: nine geolocated experiences rendered as point clouds. Concept and identity by Andrew Kastner; system developed by the studio.',
    image: `${P}/wayside/mockup-phone.jpg`,
    tone: 'wayside',
    alt: 'A phone among the reeds showing lotus buds rendered as a point cloud in augmented reality.',
    focus: '45% 50%',
    caseStudy: 'wayside',
    href: 'https://kenilworth.wayside.at',
  },
  {
    id: 'decides',
    title: 'DECIDE(S)',
    kind: 'Web application',
    year: '2026',
    lines: ['Collaborative decisions for multi-take audio production'],
    disciplines: ['Collaborative', 'Real-time', 'Web'],
    about: 'A networked workspace in which musicians, producers, and engineers review takes, score them, and record a decision together.',
    image: `${P}/decides/light-title-card.jpg`,
    tone: 'decides',
    alt: 'DECIDE(S) in light mode: an album page with its musicians and song list, above a song card beside an edit and three takes.',
    focus: '0% 20%',
    caseStudy: 'decides',
    href: 'https://decides.app',
  },
  {
    id: 'adventurous-guitar',
    title: 'Adventurous Electric Guitar',
    kind: 'Web, real-time 3D',
    client: 'Adventurous Electric Guitar Festival',
    year: '2025–26',
    lines: ['Summit + festival website', 'REMLABS'],
    disciplines: ['Web', 'Real-time', '3D'],
    about: 'Website for the Adventurous Electric Guitar summit and festival, with real-time 3D, built with REMLABS.',
    image: `${P}/adventurous-guitar/stage.jpg`,
    tone: 'aegf',
    alt: 'A stage lit in blue with guitars and amplifiers, the festival website projected above.',
    focus: '100% 50%',
    href: 'https://adventurous-guitar-2026.vercel.app',
  },
  {
    id: 'tied-to-the-land',
    title: 'Tied To The Land',
    kind: 'Exhibition',
    year: '2025',
    lines: ['Interactive exhibition map'],
    disciplines: ['Exhibition', 'Interactive', 'Map'],
    about: 'An interactive map for a gallery exhibition, presented on a touchscreen table at the centre of the room.',
    image: `${P}/tied-to-the-land/installed.jpg`,
    tone: 'tttl',
    alt: 'A gallery with framed works on the walls and a touchscreen map table at the centre of the room.',
    focus: '50% 60%',
  },
  {
    id: 'song-cards',
    title: 'Song Cards',
    kind: 'Interactive listening objects',
    year: 'In progress',
    lines: ['Songs as ornamented cards'],
    disciplines: ['Listening', 'Interactive', 'Objects'],
    about: 'Songs issued as ornamented cards; each card is an interactive object for listening. In development.',
    image: `${P}/song-cards/card.jpg`,
    tone: 'orpiment',
    alt: 'A song card: an engraved photographic image inside an ornamented frame.',
    fit: 'contain',
  },
  {
    id: 'sites-for-artists',
    title: 'Sites for artists',
    kind: 'Websites + identities',
    client: 'Ulrike Schwarz, The Twiolins, and others',
    year: '2024–26',
    lines: ['Websites and identities for', 'musicians and performers'],
    disciplines: ['Web', 'Identity', 'Design'],
    about: 'Websites and visual identities for musicians and performers, designed and built in the same studio.',
    image: `${P}/sites-for-artists/ulrike-schwarz.jpg`,
    tone: 'ulrike',
    alt: 'The home page of Ulrike Schwarz’s website: a portrait with her saxophone beside her name.',
    focus: '62% 40%',
    href: 'https://ulrikeschwarzmusik.com',
  },
  {
    id: 'earth-out-of-joint',
    title: 'Earth Out of Joint',
    kind: 'Video',
    year: '2025',
    lines: ['Video work'],
    disciplines: ['Video', 'Point', 'Cloud'],
    about: 'Video work, 2025.',
    image: `${P}/earth-out-of-joint/still.jpg`,
    tone: 'earth',
    alt: 'A still from Earth Out of Joint: fragments of the earth floating in black.',
    focus: '40% 50%',
  },
  {
    id: 'three-black-wall-streets',
    title: 'Three Black Wall Streets',
    kind: 'Web-based 3D',
    client: 'Paul Rucker',
    year: '2021',
    lines: ['For Paul Rucker'],
    disciplines: ['Web-based', '3D', 'Archive'],
    about: 'Web-based 3D for the artist Paul Rucker on the Black business districts of Durham, Richmond, and Tulsa, built from period postcards.',
    image: `${P}/three-black-wall-streets/postcards.jpg`,
    tone: 'tbws',
    alt: 'Vintage postcards for Durham, Richmond and Tulsa arranged across the landing page of Three Black Wall Streets.',
    focus: '50% 50%',
  },
  {
    id: 'white-mob-violence',
    title: 'White Mob Violence Map',
    kind: 'Geospatial visualization',
    year: '2021',
    lines: ['Geospatial visualization'],
    disciplines: ['Geospatial', 'Data', 'Visualization'],
    about: 'A geospatial visualization of white mob violence in the United States, 1824 to 1985, with each incident plotted by location.',
    image: `${P}/white-mob-violence/map.jpg`,
    tone: 'wmv',
    alt: 'A map of the United States with incidents plotted as points.',
    focus: '50% 50%',
  },
  {
    id: 'cast-down-tither',
    title: 'Cast Down Tither',
    kind: 'Performance system',
    year: '2017–',
    lines: ['Performance system'],
  },
]

/** projects with an image, in slideshow order */
export const slideshow = projects.filter((p) => p.image)
